# Generated by Django 6.1.1 on 2026-09-04 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='apellido',
            field=models.CharField(default='', max_length=200),
        ),
    ]
